### ISSUE TITLE
Task 6 - Publish mock-ups on the project repository

### ISSUE THREAD

**Issue by dbc2201** [ankita-chaudhary/expressions-based-music-player#6]
- [x] Export individual mock-up screens into separate PNG image files.
- [x] Place the images in a separate location in your repository, preferably "./images/mockups/".
- [x] Update your readme.md file, add a new heading (L3/L4) named "mock-up screens" and add the image files there, neatly labelled.

**Comment by rs714745** [comment]
completed.
